name: frontend
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0-1.1.beta

dependencies:
  jaspr: ^0.21.6
  jaspr_router: ^0.7.3
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.1
  build_web_compilers: ^4.3.0
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^6.0.0

jaspr:
  mode: client
