name: frontend
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0-1.1.beta

dependencies:
  jaspr: ^0.22.0
  jaspr_riverpod: ^0.4.1
  riverpod: ^3.0.3
  web: ^1.1.1
  common:
    path: ../common
  markdown: ^7.3.0
  http: ^1.6.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.10.1
  build_web_compilers: ^4.3.0
  jaspr_builder: ^0.22.0
  jaspr_lints: ^0.6.0
  lints: ^6.0.0

jaspr:
  mode: client
