name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  common:
    path: ../common
  shelf_limiter: ^2.0.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
